site_name: 'Untitled'
theme:
  name: material
  palette:
    scheme: preference
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
extra_css:
  - 'https://unpkg.com/mermaid@8.5.1/dist/mermaid.css'
extra_javascript:
  - 'https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'
