language: cpp
matrix:
  include:
    # macOS environment
    - os: osx
      compiler: clang
      osx_image: xcode10.3
      addons:
        homebrew:
          packages:
            - flex
            - bison
            - eigen
            - libyaml
            - libomp

    # Ubuntu 16.04 environment
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          packages:
            - autoconf
            - libtool
            - flex
            - bison
            - libeigen3-dev
            - libyaml-dev
            - libboost-all-dev
before_install:
  # Checkout Birch, which may be cached, and (re)build
  - git clone "https://github.com/lawmurray/Birch.git" || cd .
  - cd Birch && git stash && git pull && git checkout weak && ./autogen.sh && ./configure INSTALL="install -p" && make -j 2 && sudo make install && cd ..
install:
  - birch build --enable-unity && sudo birch install --enable-unity
script:
  - birch test -N 10000
cache:
  directories:
    - Birch
notifications:
  email: false
  slack:
    rooms:
      secure: QDhRPL2xS3bKMVDB1524MI3dfu+JAE8DDB/SdedB6ovH1eB9fZYpU2mG8XQN0QCA+SaxjA2SrmxC0668U2hXTv4+geneWtpMrg6oFQk5s8PhV6BcCOcFc4QfaY2W3nXdXVBEDlACYcVZd92mtZcyp8RkxJMPKWJEBu7Yg7cBFT0bWli3MqwX2+BR1CaUkUThowli9FELwpvURsxZK7bTiDS/fdQUmG7xZ1I6NkPNqs/4iMUM81dCQIrZsmrv52J2T8QYB0GM88zEoRiGsNzELQ+cQPicKvEYx2/nS3vGT403pI34KNZv+PKjc+P0M97Voj6lkP9Q4ymdbxH7NCSRZer1wzCVVl9xrcHT6fvC9mWpvIUq6im4woRLIbea6fnHVudq+6OqZup/BWXKUrPaO1npTQEtofjYyH+vCDhAbPQnEIB6zTgr9uY4Pf6aRzQtMespX5XxqR4lvt6MEw7vR0zC1nBassZypCqIz013zOpuztmOGuHy50p+PZ5EWBLgcaLl4zy/DtQ8rSludU3i27+C4SPKe8Oam+7/iA/04qQIYboKTDJijcldIXoF3MG8qoPFDaO+54hfrABt45ah/804xDVfPFeH280f9V9DdTClszRJ1SVLP8CPz+VYp/zd8CErGFIxbI9OwwOqYMBOVZJvbYxtvxgon5J3N+jU7PQ=
