language: cpp
matrix:
  include:
    # macOS environment
    - os: osx
      compiler: clang
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
            - flex
            - bison
            - eigen
            - libomp

    # Ubuntu 16.04 environment
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          packages:
            - autoconf
            - libtool
            - flex
            - bison
            - libeigen3-dev
            - libboost-all-dev
before_install:
  # Checkout Birch, which may be cached, and (re)build
  - git clone "https://github.com/lawmurray/Birch.git" || cd .
  - cd Birch && git pull && git checkout master && ./autogen.sh && ./configure INSTALL="install -p" && make -j 2 && sudo make install && cd ..

  # Checkout Birch.Standard, which may be cached, and (re)build
  - git clone "https://github.com/lawmurray/Birch.Standard.git" || cd .
  - cd Birch.Standard && git pull && git checkout master && birch build --enable-unity && sudo birch install --enable-unity && cd ..
install:
  - birch build --enable-unity && sudo birch install --enable-unity
script:
  - birch run
cache:
  directories:
    - Birch
    - Birch.Standard
notifications:
  email: false
  slack:
    rooms:
      secure: NiqT8OJQeT6vOG3PtRr0Yat6yyw+3J15wL/JObT983eckny8pNfuEoNdN1vTGxvI1Vzh3o0gfmiEtE1TicehAuqh8FXX/N51bdDOBxcVfNgDmSyk8VFR0CUMwXrJHKODyFknowuGDJanwwpD67+j58D+09DwjFibClShTrwW/u5Y6f+DGPo3lyypV8URp9Pa0UjQU68ItbzMSvUZle3YQsDV5YMTqz3Drui7CPhfHYV6z7V0zPWqFhUJG95C7goOxfIETwHjl4c08IjVvC+dCg3U+RgozhcSkZNPLSMZCNnLc4s5qdP/DToaRGf9s4IeKz7dARSeVAAVargx+05ztEJmbwrvnmiuV5S3RpeGb6NGG6V+712hHr12hXykL7rMEladwRoRUyN9ZKfRkqrvIhURCEQAAa5WEbQP2R2kTyt5Av1hww1rOZeSLPftn1KyD9hOsrP7TP4LNXwAafx/kzWVoOodcjy+Y08kOLlGOLaXotjMlxwpbdy9sD2YBmlOH7s36cn6dupSVaCzyvbTUhLxYzWekN77ovn64illf9DHbFDR5jlkmbT1o78NpSSp+ZV7+699mlIDOQQz4y12MjY02eAyp36Z+8w1dxK+rF3Big415NqBfBkvovx8z4QZFlBptYLb+yFXJPR2woROcRtSxMKfs7l6IVImWf+qqBM=
