language: cpp
matrix:
  include:
    # macOS environment
    - os: osx
      compiler: clang
      osx_image: xcode9.3

   # Ubuntu 14.04 environment
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - autoconf
            - libtool
            - flex
            - bison
            - libboost-all-dev
            - libeigen3-dev
before_install:
  - eval "${MATRIX_EVAL}"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CC=gcc-7;
      export CXX=g++-7;
      export CXXFLAGS="-DBOOST_NO_CXX11_SCOPED_ENUMS";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install flex bison eigen
    fi
  - git clone https://github.com/lawmurray/Birch.git
  - cd Birch
  - ./autogen.sh && ./configure && make -j 2 && sudo make install
  - cd ..
  - git clone https://github.com/lawmurray/Birch.Standard.git
  - cd Birch.Standard
  - birch build --disable-debug && sudo birch install
  - cd ..
install:
  - birch build --disable-debug && sudo birch install
script:
  - birch test
