language: cpp
matrix:
  include:
    # macOS environment
    - os: osx
      compiler: clang
      osx_image: xcode9.3

    # Ubuntu 14.04 environment
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - autoconf
            - libtool
            - flex
            - bison
            - libboost-all-dev
before_install:
  # OS-specific things
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CC=gcc-7;
      export CXX=g++-7;
      export CXXFLAGS="-DBOOST_NO_CXX11_SCOPED_ENUMS";
      wget http://bitbucket.org/eigen/eigen/get/3.3.4.tar.gz && tar xzf 3.3.4.tar.gz && sudo cp -Rp eigen-eigen-5a0156e40feb /usr/local/include/eigen3;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install flex bison eigen;
    fi

  # Checkout Birch, which may be cached, and (re)build
  - git clone --depth 1 "https://github.com/lawmurray/Birch.git" || (cd Birch && git fetch && cd ..)
  - cd Birch && git checkout origin/allocator && ./autogen.sh && ./configure && make -j 2 && sudo make install && cd ..
install:
  - birch build --enable-unity && sudo birch install --enable-unity
script:
  - birch test -N 10000
cache:
    directories:
     - Birch
notifications:
  email: false
  slack:
    rooms:
      secure: QDhRPL2xS3bKMVDB1524MI3dfu+JAE8DDB/SdedB6ovH1eB9fZYpU2mG8XQN0QCA+SaxjA2SrmxC0668U2hXTv4+geneWtpMrg6oFQk5s8PhV6BcCOcFc4QfaY2W3nXdXVBEDlACYcVZd92mtZcyp8RkxJMPKWJEBu7Yg7cBFT0bWli3MqwX2+BR1CaUkUThowli9FELwpvURsxZK7bTiDS/fdQUmG7xZ1I6NkPNqs/4iMUM81dCQIrZsmrv52J2T8QYB0GM88zEoRiGsNzELQ+cQPicKvEYx2/nS3vGT403pI34KNZv+PKjc+P0M97Voj6lkP9Q4ymdbxH7NCSRZer1wzCVVl9xrcHT6fvC9mWpvIUq6im4woRLIbea6fnHVudq+6OqZup/BWXKUrPaO1npTQEtofjYyH+vCDhAbPQnEIB6zTgr9uY4Pf6aRzQtMespX5XxqR4lvt6MEw7vR0zC1nBassZypCqIz013zOpuztmOGuHy50p+PZ5EWBLgcaLl4zy/DtQ8rSludU3i27+C4SPKe8Oam+7/iA/04qQIYboKTDJijcldIXoF3MG8qoPFDaO+54hfrABt45ah/804xDVfPFeH280f9V9DdTClszRJ1SVLP8CPz+VYp/zd8CErGFIxbI9OwwOqYMBOVZJvbYxtvxgon5J3N+jU7PQ=
