language: cpp
matrix:
  include:
    # macOS environment
    - os: osx
      compiler: clang
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
            - flex
            - bison
            - eigen
            - libomp
            - cairo

    # Ubuntu 16.04 environment
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          packages:
            - autoconf
            - libtool
            - flex
            - bison
            - libeigen3-dev
            - libboost-all-dev
            - libcairo2-dev
before_install:
  # Checkout Birch, which may be cached, and (re)build
  - git clone "https://github.com/lawmurray/Birch.git" || cd .
  - cd Birch && git pull && git checkout pmmh && ./autogen.sh && ./configure INSTALL="install -p" && make -j 2 && sudo make install && cd ..

  # Checkout Birch.Standard, which may be cached, and (re)build
  - git clone "https://github.com/lawmurray/Birch.Standard.git" || cd .
  - cd Birch.Standard && git pull && git checkout pmmh && birch build --enable-unity && sudo birch install --enable-unity && cd ..

  # Checkout Birch.Cairo, which may be cached, and (re)build
  - git clone "https://github.com/lawmurray/Birch.Cairo.git" || cd .
  - cd Birch.Cairo && git pull && git checkout master && birch build --enable-unity && sudo birch install --enable-unity && cd ..
install:
  - birch build --enable-unity && sudo birch install --enable-unity
script:
  - ./run.sh
cache:
  directories:
    - Birch
    - Birch.Standard
    - Birch.Cairo
notifications:
  email: false
  slack:
    secure: HNT6Bf4ANh0nANgaT80cVcHOvI1DT1EnDOBwPNMCjksWbaxTA5sUklGyUng6ZQ8BY33YEFF6MH82db4N2CQrUm1tnrgBX0KTuR1saUAVfaWnOT2ag9YW17rOLgthY6ui/6qzsiMiEvuYfXJ0z2+P4cFIjGmI2nM0bkAapKZYTrSLoIgvFteU611zQ/HI3uRwTBduBeUz3Y6xVDn4FsyPNltI5SnjRVbHHjrGUeyS0XCBKmMYTjVscP0WTd2E7M7U7uCgXLttLSwbEGeeuwZEpZFX4yGY+hOmKZuE2VLNpGCN9oI5tCckHOB2njD4QWxpZP2UwGcvJYhGa3yvubkTFAnao45aWWCOTW5LSPuCWhWUT17W7yxJQQl6gbj23KSY8rAOB4uX8pJp7Fej/C5zgvmt9Toys1QBBwyJjAMBoYf7LCrJyK2AjlLGMNRAvHQAsg/yLCpRAXP+jlq5tFGKYlc4SI3ryAnY0w9wEPSYwmLotDJs5IcST/9BGqVAa86e7tpZYBRmshhmr/jH82l+Bd7U8AJ/eP/W9W0KXj3sjYwL8rqnTUJUtEpK3eQ04ZaTnjEkLIPxujbgdImmLKR+7Id7GNJ1g2196QM65f7qqTftY/pBwF9w8U3APV2n6PnHag01dcWeBboQQhBOC62u/wXmgLpEZNYZWFN1cFLtg/8=
